#!/bin/sh
set -e
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  python-cloudfusion.public
fi
# End automatically added section
case "$1" in
    configure)
	if [ -f /usr/bin/fusermount ]
	then
		chmod o+x -f /usr/bin/fusermount
	else
		chmod o+x -f /bin/fusermount
	fi
	chmod o+rw /dev/fuse
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
