#!/bin/sh
set -e
case "$1" in
    configure)
	if [ -f /usr/bin/fusermount ]
	then
		chmod o+x -f /usr/bin/fusermount
	else
		chmod o+x -f /bin/fusermount
	fi
	chmod o+rw /dev/fuse
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	rm /usr/bin/mangafuse
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
