#!/bin/bash
PYTHON_PCK_PATH="`python -c 'import cloudfusion; print cloudfusion.__file__'`"
CONFIG_DIR=`dirname "$PYTHON_PCK_PATH"`"/config"

user="`id -un`"
has_fuse_group="`id "$user" -Gn|grep " fuse "`"
if [ -z "$has_fuse_group" ]; then
	echo "Please, run the following command if you are on Debian:"
	echo su -c "usermod -a -G fuse "`id -un`
	echo "or the following command if you are on Ubuntu:"
	echo sudo "usermod -a -G fuse "`id -un`
	echo "Then run mangafuse again."
	exit
fi
mkdir -p ~/.mangas  .cloudfusion/logs
python -m cloudfusion.main  ~/.mangas foreground >/dev/null 2>&1 &
sleep 1
cp "$CONFIG_DIR"/mangafuse.ini ~/.mangas/config/config
sleep 1
mkdir -p  ~/.mangas/data/tower\ of\ god
if [ ! -h ~/mangas ]
then
	ln -sf ~/.mangas/data ~/mangas
fi
sleep 1
if [ "`file ~/mangas|grep broken`" = "" ]
then 
    xdg-open ~/mangas 
fi


